### ISSUE TITLE
Templates are not added automatically after install

### ISSUE THREAD

**Issue by hmemcpy** [joaroyen/ReSharper.LiveTemplates#1]
Hello,

I just installed the extension in R# 9.1. Unfortunately, it seems that the templates were not loaded automatically:
![image](https://cloud.githubusercontent.com/assets/601206/8800152/113122c6-2fb9-11e5-8d2a-2cdecb179758.png)

I could add the `.dotSettings` file manually, but I'm not sure that's the correct way.

**Comment by joaroyen** [comment]
To be honest, I'm not using the provided template myself, because it just contain one simple example of how to use the macros. I recommend you create your own macros in your own dotSetting file that you can share between solutions / machines.

I have a shared.dotSettings in a Git reposiotory that I can use on all of my machines:
![image](https://cloud.githubusercontent.com/assets/70235/8826893/d4094eb0-3089-11e5-92a8-fba81786fa01.png)

I agree that the example template should be added to the Settings Layers automatically, and will look into it for the next release that will support ReSharper 9.2. In the mean time you can add it manually to the This computer node by opening C:\Users< USERNAME>\AppData\Local\JetBrains\plugins\JoarOyen.ReSharper.LiveTemplates.2.0.1.0\dotFiles\Extensions\JoarOyen.ReSharper.LiveTemplates.Example\settings\templates.dotSettings using the “plus” menu.

**Comment by joaroyen** [comment]
Version 3.0.0 will now load the example templates as a settings layer. Keep in mind that another shared settings layer with templates may interfere with the templates provided by the extension. If that happens, the template can be copied from the extension example to your own template where you also can modify it.
