### ISSUE TITLE
Not working with 2018.2

### ISSUE THREAD

**Issue by mikesigs** [joaroyen/ReSharper.LiveTemplates#5]
Hi @joaroyen. I have been using your LiveTemplates for years now. Thank you very much for them!

I just updated Resharper today to 2018.2 (using VS 15.8.28010.2003) and the templates don't appear to be working anymore. Looking in the Template Editor and the macros don't show up in the list anymore. I also tried searching in the Extensions Manager for "Joar" and got zero results.

I'm guessing there's something you gotta do to update the macro to work with the latest release? Just thought I'd put this issue here, in case you weren't already aware.

Thanks!!

**Comment by joaroyen** [comment]
Thanks for using my extension, and I appreciate feedback that publishing open source code has value to other developers :)

I haven't upgraded to 2018.2 yet but I assume I'll do that tomorrow and upgrade my extension accordingly. For every minor version of ReSharper all extensions must be updated to the latest ReSharper SDK because any given version of ReSharper only lists extension built for that version.

**Comment by mikesigs** [comment]
That makes sense. Thanks for always keeping this extension up to date man! It's always been very helpful to me. 👍

**Comment by joaroyen** [comment]
Support for ReSharper 2018.2 is now available from the ReSharper gallery.
